//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiviPrilizhenie.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonenti()
        {
            this.PortiOborudovaniya = new HashSet<PortiOborudovaniya>();
        }
    
        public System.Guid Id { get; set; }
        public string Imya { get; set; }
        public string Familia { get; set; }
        public string Otchestvo { get; set; }
        public string NomerDogovora { get; set; }
        public Nullable<System.Guid> IdPolzovatela { get; set; }
    
        public virtual Polzovateli Polzovateli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortiOborudovaniya> PortiOborudovaniya { get; set; }
        public virtual TarifiAbonentov TarifiAbonentov { get; set; }
    }
}
