//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiviPrilizhenie.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adresa()
        {
            this.UstanovlennoeOborudovanie = new HashSet<UstanovlennoeOborudovanie>();
            this.Zayavki = new HashSet<Zayavki>();
        }
    
        public System.Guid Id { get; set; }
        public string Strana { get; set; }
        public string Oblast { get; set; }
        public string Rayon { get; set; }
        public string Gorod { get; set; }
        public string Ulica { get; set; }
        public string Dom { get; set; }
        public string Dolgota { get; set; }
        public string Shirota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UstanovlennoeOborudovanie> UstanovlennoeOborudovanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayavki> Zayavki { get; set; }
    }
}
