//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiviPrilizhenie.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationContext : DbContext
    {
        private static ApplicationContext Context;
        public ApplicationContext()
            : base("name=ApplicationContext")
        {
        }
        
        public static ApplicationContext GetContext()
        {
            if (Context == null)
                Context = new ApplicationContext();
            return Context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonenti> Abonenti { get; set; }
        public virtual DbSet<Adresa> Adresa { get; set; }
        public virtual DbSet<Novosti> Novosti { get; set; }
        public virtual DbSet<Oborudovanie> Oborudovanie { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<PortiOborudovaniya> PortiOborudovaniya { get; set; }
        public virtual DbSet<RoliPolzovateley> RoliPolzovateley { get; set; }
        public virtual DbSet<SvoystvaOborudovania> SvoystvaOborudovania { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tarifi> Tarifi { get; set; }
        public virtual DbSet<TarifiAbonentov> TarifiAbonentov { get; set; }
        public virtual DbSet<TipiOborudovania> TipiOborudovania { get; set; }
        public virtual DbSet<TipiPortov> TipiPortov { get; set; }
        public virtual DbSet<TipiZayavok> TipiZayavok { get; set; }
        public virtual DbSet<UstanovlennoeOborudovanie> UstanovlennoeOborudovanie { get; set; }
        public virtual DbSet<Zayavki> Zayavki { get; set; }
        public virtual DbSet<ZnacheniyaSvoystvOborudovania> ZnacheniyaSvoystvOborudovania { get; set; }
        public virtual DbSet<ZnacheniyaSvoystvOborudovaniyaVMassive> ZnacheniyaSvoystvOborudovaniyaVMassive { get; set; }
    }
}
