//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiviPrilizhenie.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oborudovanie()
        {
            this.PortiOborudovaniya = new HashSet<PortiOborudovaniya>();
            this.UstanovlennoeOborudovanie = new HashSet<UstanovlennoeOborudovanie>();
            this.ZnacheniyaSvoystvOborudovania = new HashSet<ZnacheniyaSvoystvOborudovania>();
            this.ZnacheniyaSvoystvOborudovaniyaVMassive = new HashSet<ZnacheniyaSvoystvOborudovaniyaVMassive>();
        }
    
        public System.Guid Id { get; set; }
        public string Nazvanie { get; set; }
        public System.Guid IdTipa { get; set; }
    
        public virtual TipiOborudovania TipiOborudovania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortiOborudovaniya> PortiOborudovaniya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UstanovlennoeOborudovanie> UstanovlennoeOborudovanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZnacheniyaSvoystvOborudovania> ZnacheniyaSvoystvOborudovania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZnacheniyaSvoystvOborudovaniyaVMassive> ZnacheniyaSvoystvOborudovaniyaVMassive { get; set; }
    }
}
