//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiviPrilizhenie.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polzovateli()
        {
            this.Abonenti = new HashSet<Abonenti>();
            this.Zayavki = new HashSet<Zayavki>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdRoli { get; set; }
        public string Nomer { get; set; }
        public string Parol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonenti> Abonenti { get; set; }
        public virtual RoliPolzovateley RoliPolzovateley { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayavki> Zayavki { get; set; }
    }
}
