//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortiOborudovaniya
    {
        public System.Guid IdTipaPorta { get; set; }
        public System.Guid IdOborudovaniya { get; set; }
        public System.Guid Id { get; set; }
        public string Primechanie { get; set; }
        public string IpAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.Guid> IdAbonenta { get; set; }
    
        public virtual Abonenti Abonenti { get; set; }
        public virtual Oborudovanie Oborudovanie { get; set; }
        public virtual TipiPortov TipiPortov { get; set; }
    }
}
