//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifiAbonentov
    {
        public System.Guid IdAbonenta { get; set; }
        public System.Guid IdTarifa { get; set; }
        public System.DateTime DataPodclucheniya { get; set; }
    
        public virtual Abonenti Abonenti { get; set; }
        public virtual Tarifi Tarifi { get; set; }
    }
}
