//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UstanovlennoeOborudovanie
    {
        public System.Guid Id { get; set; }
        public string TochkaPodclucheniya { get; set; }
        public System.Guid IdAdresa { get; set; }
        public string Primechaniya { get; set; }
        public System.Guid IdOborudovaniya { get; set; }
        public System.DateTime DataUstanovki { get; set; }
        public Nullable<System.DateTime> DataDemontaza { get; set; }
    
        public virtual Adresa Adresa { get; set; }
        public virtual Oborudovanie Oborudovanie { get; set; }
    }
}
