//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavki
    {
        public System.Guid Id { get; set; }
        public string TextZayavki { get; set; }
        public System.Guid IdAdresa { get; set; }
        public System.Guid IdTipaZayavki { get; set; }
        public Nullable<System.Guid> IdPolzovatela { get; set; }
    
        public virtual Adresa Adresa { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
        public virtual TipiZayavok TipiZayavok { get; set; }
    }
}
