//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZnacheniyaSvoystvOborudovaniyaVMassive
    {
        public System.Guid IdSvoystva { get; set; }
        public System.Guid IdOborudovaniya { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<double> CifrovoeZnachenie { get; set; }
        public string TextovoeZnachenie { get; set; }
        public Nullable<bool> BoolevscoeZnachenie { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
        public virtual SvoystvaOborudovania SvoystvaOborudovania { get; set; }
    }
}
